
package pt.ist.registofatura.ws;


import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EmissorInexistente", targetNamespace = "urn:pt:registofatura:ws")
public class EmissorInexistente_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private EmissorInexistente faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public EmissorInexistente_Exception(String message, EmissorInexistente faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public EmissorInexistente_Exception(String message, EmissorInexistente faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: pt.registofatura.ws.EmissorInexistente
     */
    public EmissorInexistente getFaultInfo() {
        return faultInfo;
    }

}
